backend:
  name: github
  repo: aleksei-sorokin/gatsby
  branch: master

media_folder: static/assets/images/upload
public_folder: static/assets/images

editor:
     preview: true

collections:
  - name: vacancies
    label: Vacancies
    folder: "src/vacancies"
    create: true
    slug: "{{slug}}"
    preview_path: "/{{slug}}"
    fields:
      - { name: url, label: Url }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
