backend:
  name: github
  repo: aleksei-sorokin/gatsby.git
  branch: master

media_folder: static/assets/images/upload
public_folder: static/assets/images

collections:
  - name: vacancies
    label: Vacancies
    folder: "src/vacancies"
    create: true
    fields:
      - { name: url, label: Url }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }