backend:
  name: github
  repo: aleksei-sorokin/gatsby
  branch: master

media_folder: static/assets/images/upload
public_folder: static/assets/images

collections:
  - name: vacancies
    label: Vacancies
    folder: "src/vacancies"
    create: true
    extension: md
    slug: "{{slug}}"
    preview_path: "landings/{{permalink}}" 
    fields:
      - { name: url, label: Url }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
      - label: Permalink (e.g. "my-landing/" or "my-page/", don't forget the trailing slash!)
        name: permalink
        widget: string
        default: "my-page/"
